apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: acme-hello-app-ingress
spec:
  rules:
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              serviceName: acme-hello-app-service
              servicePort: 443